variables: secrets.yml

schedules:
  # Run TV lookup task(s) every 30 minutes
  - tasks: 'series-*'
    schedule:
      minute: "*/30"
  # Run email task every night at 10:00 PM
  - tasks: [ daily_email ]
    schedule:
      hour: 22
      minute: 0

templates:
  global:
    content_filter:
      require:
        - '*.mkv'
        - '*.avi'
        - '*.mp4'
        - '*.mp3'
        - '*.aac'
    cookies: /home/dschau/.flexget/.cookies/cookies.sqlite
  torrent_server:
    transmission:
      port: 9091
      username: '{? user ?}'
      password: '{? password ?}'
      path: '/media/TVShows/{{ series_name }}/Season {{ series_season }}/'
      # add_paused: yes
  transmission_lookup:
    disable: builtins
    metainfo_series: yes
    thetvdb_lookup: yes
    imdb_lookup: yes
    tmdb_lookup: yes
    from_transmission:
      port: 9091
      username: '{? user ?}'
      password: '{? password ?}'
      only_complete: yes
  tv:
    template: [ torrent_server ]
    include: [ series.yml ]
    thetvdb_lookup: yes
  size_limit: 
    content_size:
      min: 150
      max: 4250
      strict: no

tasks:
  series-btn:
    discover:
      what: 
        - next_series_episodes: yes
      from:
        - btn: '{? btn.apikey ?}'
      release_estimations: loose
    digest: daily email
    template: [ tv, size_limit, rssout ]
    priority: 1
    max_reruns: 3

  series_manual:
    template: [ torrent_server, rssout ]
    accept_all: yes
    thetvdb_lookup: yes
    metainfo_series: yes
    disable: [ seen ]
    manual: yes

  # movies-imdb:
  # priority: 3
  # imdb_list:
  #   login: '{{imdb.user_id}}'
  #   password: '{{imdb.password}}'
  #   list: watchlist
  #  accept_all: yes
  # # queue_movies:
  #  #   quality: 720p bluray
  #  manual: yes

  movies_manual:
    template: [ torrent_server, rssout ]
    set:
      path: '/media/Movies'
    accept_all: yes
    disable: [ seen ]
    manual: yes

  music_manual:
    template: [ torrent_server ]
    set:
      path: '/media/Music'
    accept_all: yes
    disable: [ seen ]
    manual: yes

  daily_email:
    interval: 1 days
    from_digest:
      list: daily email
      restore_state: yes
    disable: [ seen ]
    metainfo_series: yes
    thetvdb_lookup: yes
    imdb_lookup: yes
    tmdb_lookup: yes
    accept_all: yes
    notify:
      task:
        template: html-custom
        via:
          - email:
              from: '{? gmail.email ?}'
              to: '{? gmail.flexget ?}'
              smtp_host: smtp.gmail.com
              smtp_port: 587
              smtp_username: '{? gmail.username ?}'
              smtp_password: '{? gmail.password ?}'
              smtp_tls: yes
              html: yes
