presets: 
  acquired:
    trakt_acquired:
      username: USER NAME
      password: "####"
      api_key: c6b5476a17de072bf91678776b11366f
      type: series
  rssout:
    make_rss:
      file: /Users/USER NAME/Library/tmp/downloads.rss
      days: 1
  best:
    import_series:
      from:
        thetvdb_favorites:
          account_id: 0A9D2F92C462F8EB
      settings:
        upgrade: yes
        qualities:
          - 720p hdtv+
          - 720p webdl
          - 720p bluray
  release:
    series:
      settings:
        release:
          quality: 720p hdtv+
      release:
        - Louie
        - The Newsroom
        - The Soup
        - The Walking Dead
        - Workaholics
        # - The Colbert Report
        # - The Daily Show
        # - Around the Horn
        # - Pardon the Interruption
  size_limit: 
    content_size:
      min: 150
      max: 4250
      strict: no

tasks:
  btn:
    rss: https://broadcasthe.net/feeds.php?feed=torrents_notify_28109_agewu0pds3umu2if4r5oqcgfcw0aov4t&user=1495780&auth=aeb4de1b1e2a212584dbb3eb46c371ce&passkey=agewu0pds3umu2if4r5oqcgfcw0aov4t&authkey=8d8ccdea39c2bd4ce31614d28447b5b6&name=All
    priority: 1
    preset: 
      - best
      - acquired
      - size_limit
      - rssout
    thetvdb_lookup: yes
    download: /Users/USER NAME/Downloads

  tvt:
    rss: http://freshon.tv/rss.php?feed=dl
    headers:
      Cookie: "uid=210232; pass=b19d297e3da68581b81f1f4f07b02c7c"
    priority: 2
    interval: 15 minutes
    preset: 
      - best
      - release
      - acquired
      - size_limit
      - rssout
    thetvdb_lookup: yes
    download: /Users/USER NAME/Downloads

  movies:
    rss: https://www.bitleechers.me/rss.php?cat=68,67&dllink=1
    headers:
      Cookie: "passkey=d799929c4eba5ce551b38689beb36d1fdbf8aac4"
    imdb_list:
      username: USER NAME
      password: "####"
      list: watchlist
    accept_all: yes
    queue_movies:
      quality: 720p bluray
      force: yes

  trailers:
    apple_trailers: 720p
    accept_all: yes
    download: /Users/USER NAME/Movies/Trailers/
    manual: yes

  move-episodes:
    metainfo_series: yes
    accept_all: yes
    thetvdb_lookup: yes
    find:
      path: /Users/USER NAME/Downloads/Torrents/TV Shows/
      regexp: '.*(WEB.?DL|Bluray).*mkv' # only copy good quality for the external hd
      recursive: no
    move:
      to: "/Volumes/VIDEO/{{ series_name }}/{% if series_season is defined and series_season < 1000 %}Season {% else %}{% endif %}{{ series_season }}/"
      # to: "/Users/USER NAME/Movies/TV Shows/{{ series_name }}/Season {{series_season}}/"
      filename: "{% if tvdb_episode|d(false) %}E{{tvdb_episode|pad(2)}} {% if tvdb_ep_name|d(false) %}{{tvdb_ep_name}}{% endif %} {% else %}{{title}} {% endif %}" 
    manual: yes

  move-movies:
    accept_all: yes
    imdb_lookup: yes
    imdb_required: yes
    find:
      path: /Users/USER NAME/Downloads/Torrents/
      regexp: '.*(mkv|avi|mp4)'
      recursive: yes
    move:
      to: "/Volumes/Video/Movies/"
      filename: "{% if imdb_name is defined %}{{imdb_name}}{% if imdb_year is defined %}({{imdb_year}}){% endif %}{% else %}{{title}}{% endif %}"
    manual: yes

  # only need to call function when seeding db for the first time
  seed_series_db:
    find:
      regexp: .*(avi|mkv|mp4)$
      path: /Volumes/VIDEO/
      recursive: yes
    # preset: tv # need to fix for actual recognition - quality will scrwe it up
    manual: yes

  emailfeed:
    interval: 1 days
    rss:
      url: /Users/USER NAME/Library/tmp/downloads.rss
    disable_builtins: [seen]
    metainfo_series: yes # required for tvdb lookup to work, email template to function correctly
    thetvdb_lookup: yes
    accept_all: yes
    email:
      from: USER NAME@gmail.com
      to: USER NAME+flexget@gmail.com
      subject: Update of TV Shows Downloaded
      template: html_enhanced-dark
      smtp_host: smtp.gmail.com
      smtp_port: 587
      smtp_username: USER NAME
      smtp_password: "####"
      smtp_tls: yes