presets: 
  acquired:
    trakt_acquired:
      username: YOUR USER NAME
      password: "YOUR PASSWORD"
      api_key: YOUR API KEY
      type: series
  rssout:
    make_rss:
      file: /Users/YOUR USER NAME/Library/tmp/downloads.rss
      days: 1
  best:
    import_series:
      from:
        thetvdb_favorites:
          account_id: YOUR ACCOUNT ID
      settings:
        upgrade: yes
        qualities:
          - 720p hdtv+
          - 720p webdl
          - 720p bluray
  release:
    series:
      settings:
        release:
          quality: 720p hdtv+
      release:
        - Louie
        - The Newsroom
        - The Soup
        - The Walking Dead
        - Workaholics
        # - The Colbert Report
        # - The Daily Show
        # - Around the Horn
        # - Pardon the Interruption
  size_limit: 
    content_size:
      min: 150
      max: 4250
      strict: no

tasks:
  btn:
    rss: RSS FEED
    priority: 1
    preset: 
      - best
      - acquired
      - size_limit
      - rssout
    thetvdb_lookup: yes
    download: /Users/YOUR USER NAME/Downloads

  tvt:
    rss: RSS FEED
    headers:
      Cookie: "uid=####; pass=##########"
    priority: 2
    preset: 
      - best
      - release
      - acquired
      - size_limit
      - rssout
    thetvdb_lookup: yes
    download: /Users/YOUR USER NAME/Downloads

  movie_queue_imdb:
    priority: 3
    imdb_list:
      username: YOUR USER NAME
      password: YOUR PASSWORD
      list: watchlist
    accept_all: yes
    queue_movies:
      quality: 720p bluray
      force: yes

  movies:
    priority: 4
    rss: YOUR RSS
    interval: 2 hours
    headers:
      Cookie: "uid=####; pass=#############"
    # preset: size_limit
    movie_queue: yes
    seen_movies: strict
    download: /Users/YOUR USER NAME/Downloads/

  trailers:
    apple_trailers: 720p
    accept_all: yes
    download: /Users/YOUR USER NAME/Movies/Trailers/
    manual: yes

  move-episodes:
    metainfo_series: yes
    accept_all: yes
    thetvdb_lookup: yes
    find:
      path: /Users/YOUR USER NAME/Downloads/Torrents/TV Shows/
      regexp: '.*(WEB.?DL|Bluray).*mkv' # only copy good quality for the external hd
      recursive: no
    move:
      to: "/Volumes/VIDEO/{{ series_name }}/{% if series_season is defined and series_season < 1000 %}Season {% else %}{% endif %}{{ series_season }}/"
      # to: "/Users/YOUR USER NAME/Movies/TV Shows/{{ series_name }}/Season {{series_season}}/"
      filename: "{% if tvdb_episode|d(false) %}E{{tvdb_episode|pad(2)}} {% if tvdb_ep_name|d(false) %}{{tvdb_ep_name}}{% endif %} {% else %}{{title}} {% endif %}" 
    manual: yes

  move-movies:
    accept_all: yes
    imdb_lookup: yes
    imdb_required: yes
    find:
      path: /Users/YOUR USER NAME/Downloads/Torrents/
      regexp: '.*(mkv|avi|mp4)'
      recursive: yes
    move:
      to: "/Volumes/Video/Movies/"
      filename: "{% if imdb_name is defined %}{{imdb_name}}{% if imdb_year is defined %}({{imdb_year}}){% endif %}{% else %}{{title}}{% endif %}"
    manual: yes

  # only need to call function when seeding db for the first time
  seed_series_db:
    find:
      regexp: .*(avi|mkv|mp4)$
      path: /Volumes/VIDEO/
      recursive: yes
    # preset: tv # need to fix for actual recognition - quality will scrwe it up
    manual: yes

  emailfeed:
    interval: 1 days
    rss:
      url: /Users/YOUR USER NAME/Library/tmp/downloads.rss
    disable_builtins: [seen]
    metainfo_series: yes # required for tvdb lookup to work, email template to function correctly
    thetvdb_lookup: yes
    accept_all: yes
    email:
      from: YOUR USER NAME
      to: YOUR EMAIL
      subject: Downloaded Media Update
      template: html_enhanced-dark
      smtp_host: smtp.gmail.com
      smtp_port: 587
      smtp_username: YOUR USER NAME
      smtp_password: YOUR PASSWORD
      smtp_tls: yes