variables: secrets.yml

schedules:
  # Run TV lookup task(s) every 30 minutes
  - tasks: 'tv-*'
    schedule:
      minute: "*/30"
  # Run Movie lookup task(s) every hour
  - tasks: 'movie-*'
    schedule:
      minute: "*/60"
  # Run email task every night at 10:00 PM
  - tasks: [ daily-email ]
    schedule:
      hour: 22
      minute: 0

templates:
  global:
    content_filter:
      require:
        - '*.mkv'
        - '*.avi'
        - '*.mp4'
        - '*.mp3'
        - '*.aac'
    cookies: /home/dschau/.flexget/.cookies/cookies.sqlite
  torrent_server:
    transmission:
      port: 9091
      username: '{? user ?}'
      password: '{? password ?}'
      path: '/media/TVShows/{{ series_name }}/Season {{ series_season }}/'
  transmission_lookup:
    disable: builtins
    metainfo_series: yes
    thetvdb_lookup: yes
    imdb_lookup: yes
    tmdb_lookup: yes
    from_transmission:
      port: 9091
      username: '{? user ?}'
      password: '{? password ?}'
      only_complete: yes
  tv:
    template: [ torrent_server ]
    include: [ series.yml ]
    thetvdb_lookup: yes
  size_limit: 
    content_size:
      min: 150
      max: 4250
      strict: no

tasks:
  tv__manual:
    thetvdb_lookup: yes
    csv:
      url: '{? csv.shows ?}'
      values:
        title: 1
        url: 1
        begin: 2
    accept_all: yes
    list_add:
      - entry_list: entries
    manual: yes

  tv-btn:
    template: [ tv, size_limit ]
    priority: 1
    discover:
      what: 
        - next_series_episodes: yes
      from:
        - btn: '{? btn.apikey ?}'
      release_estimations: loose
    digest: daily email
    max_reruns: 3

  movie-requests:
    priority: 1
    imdb_lookup: yes
    csv:
      url: '{? csv.movies.requests ?}'
      values:
        title: 2
        url: 2
    accept_all: yes
    seen: local
    list_add:
      - movie_list: movie_requests

  movie-ptp:
    priority: 2
    template: [ torrent_server ]
    set:
      path: '/media/Movies'
      add_paused: yes
    discover:
      what:
        - limit:
            amount: 50
            from:
              movie_list: movie_queue
      from:
        - passthepopcorn:
            username: '{? ptp.username ?}'
            password: '{? ptp.password ?}'
            passkey: '{? ptp.passkey ?}'
            order_by: Seeders
    imdb_lookup: yes
    torrent_alive: 10
    quality:
      - 720p bluray
    digest: daily email
    list_match:
      from:
        - movie_list: movie_queue

  daily-email:
    from_digest:
      list: daily email
      limit: 50
      restore_state: yes
    disable: [ seen ]
    metainfo_series: yes
    thetvdb_lookup: yes
    imdb_lookup: yes
    tmdb_lookup: yes
    accept_all: yes
    notify:
      task:
        template: html-custom
        via:
          - email:
              from: '{? gmail.email ?}'
              to: '{? gmail.flexget ?}'
              smtp_host: smtp.gmail.com
              smtp_port: 587
              smtp_username: '{? gmail.username ?}'
              smtp_password: '{? gmail.password ?}'
              smtp_tls: yes
              html: yes
